(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))

;; (require 'init-package)
(require 'init-stright)
(require 'init-quelpa)
(require 'init-bookmark+)
;; (require 'init-disable-project)
;; (require 'init-projectile)

(require 'init-utils)
(require 'init-elpa)
;; (require 'init-ido)
(require 'init-exec-path)
(require 'init-kill-ring)
;;----------------------------------------------------------------------------
;; Load configs for specific features and modes
;;----------------------------------------------------------------------------

;; (require-package 'wgrep)
;; (require-package 'project-local-variables)
;; (require-package 'diminish)
;; (require-package 'scratch)
;; (require-package 'mwe-log-commands)

;; (require 'init-frame-hooks)
;; (require 'init-xterm)
;; (require 'init-osx-keys)
;; (require 'init-gui-frames)
;; (require 'init-proxies)
;; (require 'init-isearch)
;; (require 'init-uniquify)
;; (require 'init-ibuffer)
;; (require 'init-flycheck)
(require 'init-git)
(require 'init-gdb)
(require 'init-recentf)
;; (require 'init-gui)
(require 'init-misc)
;; (require 'init-eat)
;; (require 'init-xcscope)
(require 'init-xxcscope)
;; (require 'init-hippie-expand)

;; (require 'init-windows)
;; (require 'init-sessions)
;; (require 'init-mmm)
(require 'init-editing-utils)

;; (require 'init-vc)
;; (require 'init-darcs)

;; (require 'init-crontab)
;; (require 'init-textile)
;; (require 'init-csv)
;; (require 'init-erlang)
;; (require 'init-javascript)
;; (require 'init-php)
(require 'init-org)
;; (require 'init-nxml)
;; (require 'init-html)
;; (require 'init-css)
;; (require 'init-haml)
;; (require 'init-python-mode)
;; (require 'init-ruby-mode)
;; (require 'init-rails)
;; (require 'init-sql)

;; (require 'init-paredit)
;; (require 'init-lisp)
;; (require 'init-slime)
;; (require 'init-clojure)
;; (when (>= emacs-major-version 24)
;;   (require 'init-clojure-cider))
;; (require 'init-common-lisp)

;; (require 'init-marmalade)
;; (require 'init-misc)

;; (require 'init-dash)
;; (require 'init-ledger)
;; ;; Extra packages which don't require any configuration

;; (require-package 'gnuplot)
;; (require-package 'lua-mode)
;; (require-package 'htmlize)
;; (require-package 'dsvn)
;; (require-package 'regex-tool)
;; (require 'init-ccmode)
;; (require 'init-hooks)
(require 'init-fonts)
(require 'init-themes)
(require 'init-yasnippet)
;; (require 'init-flymake)
;; (require 'init-chatgpt)
(require 'init-dts)
(require 'init-ivy)
;; (require 'init-helm)
(require 'init-clangfmt)
;; (require 'init-ace-window)
;; (require 'init-bookmark+)
(require 'init-undo-tree)
(require 'init-smartparens)
;; (require 'init-lspccls)
(require 'init-lsp-bridge)
;; (require 'init-largefiles)
(require 'init-grip-mode)
(require 'init-startup-window)
(require 'init-xml)
(require 'init-perspective)
(require 'init-ansi-color)
(require 'init-bm)
(require 'init-linkmarks)

(require 'init-swift)
(require 'init-groovy)
(require 'init-markdown)
(require 'init-dart)
;; (require 'init-imenu-list)
(require 'init-resize-window)
(require 'init-highlight-indent-guides)
;; (require 'init-indent-bars)


(require 'init-eshell)
