;; 初始化包管理
(require 'package)
(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("gnu" . "https://elpa.gnu.org/packages/")))
(package-initialize)

;; 确保 use-package 已安装和加载
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(require 'use-package)
(setq use-package-always-ensure t)

(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))

(require 'init-utils)
(require 'init-elpa)
(require 'init-quelpa)
;; (require 'init-ido)
(require 'init-exec-path)
(require 'init-kill-ring)
;;----------------------------------------------------------------------------
;; Load configs for specific features and modes
;;----------------------------------------------------------------------------

;; (require-package 'wgrep)
;; (require-package 'project-local-variables)
;; (require-package 'diminish)
;; (require-package 'scratch)
;; (require-package 'mwe-log-commands)

;; (require 'init-frame-hooks)
;; (require 'init-xterm)
;; (require 'init-osx-keys)
;; (require 'init-gui-frames)
;; (require 'init-proxies)
;; (require 'init-isearch)
;; (require 'init-uniquify)
;; (require 'init-ibuffer)
;; (require 'init-flycheck)
(require 'init-git)
(require 'init-gdb)
(require 'init-recentf)
;; (require 'init-gui)
(require 'init-misc)
(require 'init-eshell)
;; (require 'init-xcscope)
(require 'init-xxcscope)
;; (require 'init-hippie-expand)

;; (require 'init-windows)
;; (require 'init-sessions)
;; (require 'init-mmm)
(require 'init-editing-utils)

;; (require 'init-vc)
;; (require 'init-darcs)

;; (require 'init-crontab)
;; (require 'init-textile)
;; (require 'init-csv)
;; (require 'init-erlang)
;; (require 'init-javascript)
;; (require 'init-php)
(require 'init-org)
;; (require 'init-nxml)
;; (require 'init-html)
;; (require 'init-css)
;; (require 'init-haml)
;; (require 'init-python-mode)
;; (require 'init-ruby-mode)
;; (require 'init-rails)
;; (require 'init-sql)

;; (require 'init-paredit)
;; (require 'init-lisp)
;; (require 'init-slime)
;; (require 'init-clojure)
;; (when (>= emacs-major-version 24)
;;   (require 'init-clojure-cider))
;; (require 'init-common-lisp)

;; (require 'init-marmalade)
;; (require 'init-misc)

;; (require 'init-dash)
;; (require 'init-ledger)
;; ;; Extra packages which don't require any configuration

;; (require-package 'gnuplot)
;; (require-package 'lua-mode)
;; (require-package 'htmlize)
;; (require-package 'dsvn)
;; (require-package 'regex-tool)
;; (require 'init-ccmode)
;; (require 'init-hooks)
(require 'init-fonts)
(require 'init-themes)
(require 'init-yasnippet)
;; (require 'init-flymake)
;; (require 'init-chatgpt)
(require 'init-dts)
(require 'init-ivy)
;; (require 'init-helm)
(require 'init-lspccls)
(require 'init-largefiles)
(require 'init-clangfmt)
(require 'init-hydra)
(require 'init-ace-window)
(require 'init-bookmark+)
(require 'init-undo-tree)
(require 'init-smartparens)
