(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))

;; (require 'init-package)
(require 'init-straight)
;; (require 'init-quelpa)
(require 'init-bookmark+)
(require 'init-zmq)

(require 'init-utils)
(require 'init-elpa)
(require 'init-exec-path)
(require 'init-kill-ring)

(require 'init-git)
(require 'init-gdb)
(require 'init-recentf)
(require 'init-misc)
(require 'init-xxcscope)
(require 'init-editing-utils)
(require 'init-org)
(require 'init-fonts)
(require 'init-themes)
(require 'init-yasnippet)
(require 'init-dts)
;; (require 'init-ivy)
(require 'init-vertico)
(require 'init-clangfmt)
(require 'init-undo-tree)
(require 'init-smartparens)
(require 'init-lsp-bridge)
(require 'init-grip-mode)
(require 'init-startup-window)
(require 'init-xml)
(require 'init-perspective)
(require 'init-ansi-color)
(require 'init-bm)
(require 'init-linkmarks)
(require 'init-swift)
(require 'init-groovy)
(require 'init-markdown)
(require 'init-dart)
(require 'init-resize-window)
(require 'init-highlight-indent-guides)

(require 'init-eshell)
(require 'init-pyenv)
(require 'init-jupyter)
(require 'init-embark)
(require 'init-org-roam)

;; (require 'init-gptel)
;; (require 'init-codeium)

