(require-package 'switch-window)
;; (require 'switch-window-autoloads)
(global-set-key (kbd "C-x o") 'switch-window)
(global-set-key (kbd "C-x 0") 'switch-window-then-delete)
(provide 'init-switch-window)
